### ISSUE TITLE
SQLSTATE[08004] [1040] Too many connections

### ISSUE THREAD

**Issue by mookman288** [ParticleBits/pdo#4]
Hi,

This is a weird intermittent issue, and I'm hoping someone else can provide context because I'm having real trouble figuring this out.

When I'm using FaaPz/Slim-PDO, I don't encounter this issue. With the forked library, the issue is intermittent, but it seems to be completely random as to when it occurs. I cannot replicate the issue, but it happens repeatedly. 

I'm wondering if changes have been made to the way connections are created and potentially released? I know PHP's garbage collection should typically take care of outstanding issues like this. I was just curious if anyone else has encountered this.

**Comment by mikegioia** [comment]
@mookman288 Could you do me a favor and check what your mysqld config setting is for `max_connections`? I set mine high, but it could be related: https://dev.mysql.com/doc/refman/5.5/en/too-many-connections.html

**Comment by mookman288** [comment]
@mikegioia I've got it at 500 right now, up from 300. 

EDIT: also I double checked, and I am reusing the connection throughout each request instead of starting a new connection each time.

**Comment by mikegioia** [comment]
Wow, weird. I don't know to be honest, because this fork doesn't/didn't change any connection code. There really isn't even any connection code, it's a thin wrapper around the native PDO library.

I think the only way to really diagnose this would be to write some custom test script that opened a lot of connections and executed a bunch of queries. I've been running this fork in a number of different environments and I haven't hit this particular issue yet.
